source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SUImageComparisonView_Example', :exclusive => true do
  pod "SUImageComparisonView", :path => "../"
end

target 'SUImageComparisonView_Tests', :exclusive => true do
  pod "SUImageComparisonView", :path => "../"

  
end
